# ~/.config/starship.toml

# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[username]
disabled = false
show_always = true

[c]
symbol = "ğŸ¦ "
# the commands of the Tiny C Compiler
# commands = [["tcc", "-vv"]]

[cmake]
symbol = "ğŸ "

[dotnet]
symbol= "ğŸ¥… "

[erlang]
symbol = "ğŸ“ "

[git_metrics]
disabled = false

[haskell]
symbol = "ğŸ¦ˆ "

[helm]
symbol = "ğŸœ "

[julia]
symbol = "ğŸ¦— "

[kotlin]
symbol = "ğŸ™ "

[nodejs]
symbol = "ğŸ "

[purescript]
symbol = "ğŸ¦š"

[scala]
symbol = "ğŸ¦Ÿ "

[vlang]
symbol = "ğŸ¦¦ "

[zig]
symbol = "ğŸ¦ "

[buf]
symbol = "ğŸ‚ "