# ~/.config/starship.toml

# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[username]
disabled = false
show_always = true

[c]
symbol = "ğŸš€ "
# the commands of the Tiny C Compiler
# commands = [["tcc", "-vv"]]

[cmake]
symbol = "ğŸ "

[dotnet]
symbol= "ğŸ¥… "

[erlang]
symbol = "ğŸ“ "

# [git_status]
# conflicted = "ğŸš©"
# ahead = "ğŸ’¨"
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
# up_to_date = "ğŸ‘Œ"
# untracked = "ğŸ¤·"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged = '[++\($count\)](green)'
# renamed = "ğŸ‘…"
# deleted = "ğŸ˜"

[haskell]
symbol = "ğŸ¦ˆ "

[helm]
symbol = "ğŸœ "

[julia]
symbol = "ğŸ“Š "

[kotlin]
symbol = "ğŸ™ "

[nodejs]
symbol = "ğŸ "

[purescript]
symbol = "ğŸ¦š"

[scala]
symbol = "ğŸ“ "

[vlang]
symbol = "ğŸ¦¦"

[zig]
symbol = "ğŸ¦ "

[buf]
symbol = "ğŸ‚"

# [custom.clanguage]
# command = "echo ğŸŒŒ v$(tcc -v | cut -d ' ' -f 3)"
# extensions = ["c", "h"]
# style = "bold blue"
