# ~/.config/starship.toml
 
[username]
disabled = false
show_always = true

[c]
symbol = "ğŸŒŒ "
# the commands of the Tiny C Compiler
# commands = [["tcc", "-vv"]]

[cmake]
symbol = "ğŸ "

[dotnet]
symbol= "ğŸ¥… "

[julia]
symbol = "ğŸ¦— "

[nodejs]
symbol = "ğŸ "
